/*
 * This file is generated by jOOQ.
 */
package com.benwon.shop.entity;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Data;
@Data
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler"})

/**
 * 商品表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "product", schema = "shop", uniqueConstraints = {
    @UniqueConstraint(name = "KEY_product_PRIMARY", columnNames = {"id"})
}, indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "id ASC")
})
public class Product implements Serializable {

    private static final long serialVersionUID = 961961050;

    private String        id;
    private String        productName;
    private Long          productImgId;
    private String        productImgResourceUrl;
    private Integer       salePrice;
    private Integer       discPrice;
    private LocalDate     expiryDate;
    private String        basicUnitDesc;
    private String        norm;
    private String        productIntroduction;
    private String        introduction;
    private String        specifications;
    private String        createdBy;
    private LocalDateTime createdDate;
    private String        lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public Product() {}

    public Product(Product value) {
        this.id = value.id;
        this.productName = value.productName;
        this.productImgId = value.productImgId;
        this.productImgResourceUrl = value.productImgResourceUrl;
        this.salePrice = value.salePrice;
        this.discPrice = value.discPrice;
        this.expiryDate = value.expiryDate;
        this.basicUnitDesc = value.basicUnitDesc;
        this.norm = value.norm;
        this.productIntroduction = value.productIntroduction;
        this.introduction = value.introduction;
        this.specifications = value.specifications;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public Product(
        String        id,
        String        productName,
        Long          productImgId,
        String        productImgResourceUrl,
        Integer       salePrice,
        Integer       discPrice,
        LocalDate     expiryDate,
        String        basicUnitDesc,
        String        norm,
        String        productIntroduction,
        String        introduction,
        String        specifications,
        String        createdBy,
        LocalDateTime createdDate,
        String        lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.id = id;
        this.productName = productName;
        this.productImgId = productImgId;
        this.productImgResourceUrl = productImgResourceUrl;
        this.salePrice = salePrice;
        this.discPrice = discPrice;
        this.expiryDate = expiryDate;
        this.basicUnitDesc = basicUnitDesc;
        this.norm = norm;
        this.productIntroduction = productIntroduction;
        this.introduction = introduction;
        this.specifications = specifications;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "product_name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    @Column(name = "product_img_id", nullable = false, precision = 19)
    @NotNull
    public Long getProductImgId() {
        return this.productImgId;
    }

    public void setProductImgId(Long productImgId) {
        this.productImgId = productImgId;
    }

    @Column(name = "product_img_resource_url", nullable = false, length = 300)
    @NotNull
    @Size(max = 300)
    public String getProductImgResourceUrl() {
        return this.productImgResourceUrl;
    }

    public void setProductImgResourceUrl(String productImgResourceUrl) {
        this.productImgResourceUrl = productImgResourceUrl;
    }

    @Column(name = "sale_price", nullable = false, precision = 10)
    @NotNull
    public Integer getSalePrice() {
        return this.salePrice;
    }

    public void setSalePrice(Integer salePrice) {
        this.salePrice = salePrice;
    }

    @Column(name = "disc_price", nullable = false, precision = 10)
    @NotNull
    public Integer getDiscPrice() {
        return this.discPrice;
    }

    public void setDiscPrice(Integer discPrice) {
        this.discPrice = discPrice;
    }

    @Column(name = "expiry_date", nullable = false)
    @NotNull
    public LocalDate getExpiryDate() {
        return this.expiryDate;
    }

    public void setExpiryDate(LocalDate expiryDate) {
        this.expiryDate = expiryDate;
    }

    @Column(name = "basic_unit_desc", nullable = false, length = 20)
    @NotNull
    @Size(max = 20)
    public String getBasicUnitDesc() {
        return this.basicUnitDesc;
    }

    public void setBasicUnitDesc(String basicUnitDesc) {
        this.basicUnitDesc = basicUnitDesc;
    }

    @Column(name = "norm", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getNorm() {
        return this.norm;
    }

    public void setNorm(String norm) {
        this.norm = norm;
    }

    @Column(name = "product_introduction", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getProductIntroduction() {
        return this.productIntroduction;
    }

    public void setProductIntroduction(String productIntroduction) {
        this.productIntroduction = productIntroduction;
    }

    @Column(name = "introduction", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getIntroduction() {
        return this.introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    @Column(name = "specifications", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getSpecifications() {
        return this.specifications;
    }

    public void setSpecifications(String specifications) {
        this.specifications = specifications;
    }

    @Column(name = "created_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "created_date", nullable = false)
    @NotNull
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "last_modified_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    @Column(name = "last_modified_date", nullable = false)
    @NotNull
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}
