/*
 * This file is generated by jOOQ.
 */
package com.benwon.shop.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import lombok.Data;

@Data

/**
 * 銷售訂單表
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.12.3" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "sale_order", uniqueConstraints = {
		@UniqueConstraint(name = "KEY_sale_order_PRIMARY", columnNames = { "id" }) }, indexes = {
				@Index(name = "PRIMARY", unique = true, columnList = "id ASC") })
public class SaleOrder implements Serializable {

	private static final long serialVersionUID = -808633762;
	@Id
	@Column(name = "id", nullable = false, length = 36)
	@NotNull
	@Size(max = 36)
	private String id;
	@Column(name = "purchaser_user_id", nullable = false, length = 36)
	@NotNull
	@Size(max = 36)
	private String purchaserUserId;
	@Column(name = "receiver_name", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	private String receiverName;
	@Column(name = "mobile_phone", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	private String mobilePhone;
	@Column(name = "county", length = 20)
	@Size(max = 20)
	private String county;
	@Column(name = "district", length = 20)
	@Size(max = 20)
	private String district;
	@Column(name = "zipcode", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	private String zipcode;
	@Column(name = "receiver_address", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	private String receiverAddress;
	@Column(name = "remark", length = 200)
	@Size(max = 200)
	private String remark;
	@Column(name = "consumption_amount", nullable = false, precision = 10)
	@NotNull
	private Integer consumptionAmount;
	@Column(name = "freight_amount", nullable = false, precision = 10)
	@NotNull
	private Integer freightAmount;
	@Column(name = "order_amount", nullable = false, precision = 10)
	@NotNull
	private Integer orderAmount;
	@Column(name = "pay_state", nullable = false, precision = 10)
	@NotNull
	private Integer payState;
	@Column(name = "is_shipped", nullable = false, precision = 10)
	@NotNull
	private Integer isShipped;
	@Column(name = "show_purchaser_user", nullable = false, precision = 10)
	@NotNull
	private Integer showPurchaserUser;
	@Column(name = "created_by", nullable = false, length = 60)
	@NotNull
	@Size(max = 60)
	private String createdBy;
	@Column(name = "created_date", nullable = false)
	@NotNull
	private LocalDateTime createdDate;
	@Column(name = "last_modified_by", nullable = false, length = 60)
	@NotNull
	@Size(max = 60)
	private String lastModifiedBy;
	@Column(name = "last_modified_date", nullable = false)
	@NotNull
	private LocalDateTime lastModifiedDate;
}