/*
 * This file is generated by jOOQ.
 */
package com.benwon.shop.entity;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 網站入口銷售頁
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "sale_portal", schema = "shop", uniqueConstraints = {
    @UniqueConstraint(name = "KEY_sale_portal_PRIMARY", columnNames = {"id"})
}, indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "id ASC"),
    @Index(name = "product_id", columnList = "product_id ASC")
})
public class SalePortal implements Serializable {

    private static final long serialVersionUID = 731394491;

    private String        id;
    private String        productId;
    private Integer       sorting;
    private LocalDateTime saleStartDate;
    private LocalDateTime saleEndDate;
    private Integer       saleStatus;
    private String        createdBy;
    private LocalDateTime createdDate;
    private String        lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public SalePortal() {}

    public SalePortal(SalePortal value) {
        this.id = value.id;
        this.productId = value.productId;
        this.sorting = value.sorting;
        this.saleStartDate = value.saleStartDate;
        this.saleEndDate = value.saleEndDate;
        this.saleStatus = value.saleStatus;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public SalePortal(
        String        id,
        String        productId,
        Integer       sorting,
        LocalDateTime saleStartDate,
        LocalDateTime saleEndDate,
        Integer       saleStatus,
        String        createdBy,
        LocalDateTime createdDate,
        String        lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.id = id;
        this.productId = productId;
        this.sorting = sorting;
        this.saleStartDate = saleStartDate;
        this.saleEndDate = saleEndDate;
        this.saleStatus = saleStatus;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "product_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    @Column(name = "sorting", nullable = false, precision = 10)
    @NotNull
    public Integer getSorting() {
        return this.sorting;
    }

    public void setSorting(Integer sorting) {
        this.sorting = sorting;
    }

    @Column(name = "sale_start_date", nullable = false)
    @NotNull
    public LocalDateTime getSaleStartDate() {
        return this.saleStartDate;
    }

    public void setSaleStartDate(LocalDateTime saleStartDate) {
        this.saleStartDate = saleStartDate;
    }

    @Column(name = "sale_end_date", nullable = false)
    @NotNull
    public LocalDateTime getSaleEndDate() {
        return this.saleEndDate;
    }

    public void setSaleEndDate(LocalDateTime saleEndDate) {
        this.saleEndDate = saleEndDate;
    }

    @Column(name = "sale_status", nullable = false, precision = 10)
    @NotNull
    public Integer getSaleStatus() {
        return this.saleStatus;
    }

    public void setSaleStatus(Integer saleStatus) {
        this.saleStatus = saleStatus;
    }

    @Column(name = "created_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "created_date", nullable = false)
    @NotNull
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "last_modified_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    @Column(name = "last_modified_date", nullable = false)
    @NotNull
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}
