/*
 * This file is generated by jOOQ.
 */
package com.benwon.shop.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Data;

/**
 * 訂單明細表
 */
@Data
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.12.3" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "sale_order_detail", uniqueConstraints = {
		@UniqueConstraint(name = "KEY_sale_order_detail_PRIMARY", columnNames = { "id" }) }, indexes = {
				@Index(name = "PRIMARY", unique = true, columnList = "id ASC"),
				@Index(name = "product_id", columnList = "product_id ASC"),
				@Index(name = "product_item_id", columnList = "product_item_id ASC") })
public class SaleOrderDetail implements Serializable {

	private static final long serialVersionUID = -66010411;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false, precision = 19)
	private Long id;
	@Column(name = "order_id", nullable = false, length = 36)
	@NotNull
	@Size(max = 36)
	private String orderId;
	@Column(name = "product_id", nullable = false, length = 36)
	@NotNull
	@Size(max = 36)
	private String productId;
	@Column(name = "product_name", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	private String productName;
	@Column(name = "product_item_id", nullable = false, length = 36)
	@NotNull
	@Size(max = 36)
	private String productItemId;
	@Column(name = "product_item_name", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	private String productItemName;
	@Column(name = "sales_unit", nullable = false, precision = 10)
	@NotNull
	private Integer salesUnit;
	@Column(name = "sales_unit_desc", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	private String salesUnitDesc;
	@Column(name = "unit_count", nullable = false, precision = 10)
	@NotNull
	private Integer unitCount;
	@Column(name = "subtotal", nullable = false, precision = 10)
	@NotNull
	private Integer subtotal;
	@Column(name = "is_shipped", nullable = false, precision = 10)
	@NotNull
	private Integer isShipped;
	@Column(name = "ref_sale_group_id", length = 36)
	@Size(max = 36)
	private String refSaleGroupId;
	@Column(name = "created_by", nullable = false, length = 60)
	@NotNull
	@Size(max = 60)
	private String createdBy;
	@Column(name = "created_date", nullable = false)
	@NotNull
	private LocalDateTime createdDate;
	@Column(name = "last_modified_by", nullable = false, length = 60)
	@NotNull
	@Size(max = 60)
	private String lastModifiedBy;
	@Column(name = "last_modified_date", nullable = false)
	@NotNull
	private LocalDateTime lastModifiedDate;
}