/*
 * This file is generated by jOOQ.
 */
package com.benwon.shop.entity;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 銷售目錄頁商品
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "sale_group_items", schema = "shop", uniqueConstraints = {
    @UniqueConstraint(name = "KEY_sale_group_items_PRIMARY", columnNames = {"id"})
}, indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "id ASC"),
    @Index(name = "product_id", columnList = "product_id ASC"),
    @Index(name = "sale_group_id", columnList = "sale_group_id ASC")
})
public class SaleGroupItems implements Serializable {

    private static final long serialVersionUID = 564442693;

    private Long          id;
    private String        saleGroupId;
    private String        productId;
    private Integer       sorting;
    private String        createdBy;
    private LocalDateTime createdDate;
    private String        lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public SaleGroupItems() {}

    public SaleGroupItems(SaleGroupItems value) {
        this.id = value.id;
        this.saleGroupId = value.saleGroupId;
        this.productId = value.productId;
        this.sorting = value.sorting;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public SaleGroupItems(
        Long          id,
        String        saleGroupId,
        String        productId,
        Integer       sorting,
        String        createdBy,
        LocalDateTime createdDate,
        String        lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.id = id;
        this.saleGroupId = saleGroupId;
        this.productId = productId;
        this.sorting = sorting;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, precision = 19)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "sale_group_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getSaleGroupId() {
        return this.saleGroupId;
    }

    public void setSaleGroupId(String saleGroupId) {
        this.saleGroupId = saleGroupId;
    }

    @Column(name = "product_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    @Column(name = "sorting", nullable = false, precision = 10)
    @NotNull
    public Integer getSorting() {
        return this.sorting;
    }

    public void setSorting(Integer sorting) {
        this.sorting = sorting;
    }

    @Column(name = "created_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "created_date", nullable = false)
    @NotNull
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "last_modified_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    @Column(name = "last_modified_date", nullable = false)
    @NotNull
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}
