/*
 * This file is generated by jOOQ.
 */
package com.benwon.shop.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * 簡訊發送紀錄
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.12.3" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "sms_record", uniqueConstraints = {
		@UniqueConstraint(name = "KEY_sms_record_PRIMARY", columnNames = { "id" }) }, indexes = {
				@Index(name = "PRIMARY", unique = true, columnList = "id ASC") })
public class SmsRecord implements Serializable {

	private static final long serialVersionUID = 1139135330;

	private String id;
	private String phoneNumber;
	private String verificationCode;
	private Integer verfyStatus;
	private String createdBy;
	private LocalDateTime createdDate;
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;

	public SmsRecord() {
	}

	public SmsRecord(SmsRecord value) {
		this.id = value.id;
		this.phoneNumber = value.phoneNumber;
		this.verificationCode = value.verificationCode;
		this.verfyStatus = value.verfyStatus;
		this.createdBy = value.createdBy;
		this.createdDate = value.createdDate;
		this.lastModifiedBy = value.lastModifiedBy;
		this.lastModifiedDate = value.lastModifiedDate;
	}

	public SmsRecord(String id, String phoneNumber, String verificationCode, Integer verfyStatus, String createdBy,
			LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate) {
		this.id = id;
		this.phoneNumber = phoneNumber;
		this.verificationCode = verificationCode;
		this.verfyStatus = verfyStatus;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@Column(name = "id", nullable = false, length = 60)
	@NotNull
	@Size(max = 60)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "phone_number", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "verification_code", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getVerificationCode() {
		return this.verificationCode;
	}

	public void setVerificationCode(String verificationCode) {
		this.verificationCode = verificationCode;
	}

	@Column(name = "verfy_status", nullable = false, precision = 10)
	@NotNull
	public Integer getVerfyStatus() {
		return this.verfyStatus;
	}

	public void setVerfyStatus(Integer verfyStatus) {
		this.verfyStatus = verfyStatus;
	}

	@Column(name = "created_by", nullable = false, length = 60)
	@NotNull
	@Size(max = 60)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_date", nullable = false)
	@NotNull
	public LocalDateTime getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(LocalDateTime createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "last_modified_by", nullable = false, length = 60)
	@NotNull
	@Size(max = 60)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Column(name = "last_modified_date", nullable = false)
	@NotNull
	public LocalDateTime getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}
}
