/*
 * This file is generated by jOOQ.
 */
package com.benwon.shop.entity;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 使用者資料
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "user_profile", schema = "shop", uniqueConstraints = {
    @UniqueConstraint(name = "KEY_user_profile_PRIMARY", columnNames = {"id"})
}, indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "id ASC")
})
public class UserProfile implements Serializable {

    private static final long serialVersionUID = 1303150994;

    private String        id;
    private String        realName;
    private String        nickName;
    private String        picture;
    private String        lineId;
    private String        lineUserId;
    private String        lineUserName;
    private String        mobilePhone;
    private String        email;
    private String        county;
    private String        district;
    private String        zipcode;
    private String        address;
    private Integer       finished;
    private String        createdBy;
    private LocalDateTime createdDate;
    private String        lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public UserProfile() {}

    public UserProfile(UserProfile value) {
        this.id = value.id;
        this.realName = value.realName;
        this.nickName = value.nickName;
        this.picture = value.picture;
        this.lineId = value.lineId;
        this.lineUserId = value.lineUserId;
        this.lineUserName = value.lineUserName;
        this.mobilePhone = value.mobilePhone;
        this.email = value.email;
        this.county = value.county;
        this.district = value.district;
        this.zipcode = value.zipcode;
        this.address = value.address;
        this.finished = value.finished;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public UserProfile(
        String        id,
        String        realName,
        String        nickName,
        String        picture,
        String        lineId,
        String        lineUserId,
        String        lineUserName,
        String        mobilePhone,
        String        email,
        String        county,
        String        district,
        String        zipcode,
        String        address,
        Integer       finished,
        String        createdBy,
        LocalDateTime createdDate,
        String        lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.id = id;
        this.realName = realName;
        this.nickName = nickName;
        this.picture = picture;
        this.lineId = lineId;
        this.lineUserId = lineUserId;
        this.lineUserName = lineUserName;
        this.mobilePhone = mobilePhone;
        this.email = email;
        this.county = county;
        this.district = district;
        this.zipcode = zipcode;
        this.address = address;
        this.finished = finished;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    @Id
    @Column(name = "id", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "real_name", length = 100)
    @Size(max = 100)
    public String getRealName() {
        return this.realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    @Column(name = "nick_name", length = 100)
    @Size(max = 100)
    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    @Column(name = "picture", length = 300)
    @Size(max = 300)
    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    @Column(name = "line_id", length = 100)
    @Size(max = 100)
    public String getLineId() {
        return this.lineId;
    }

    public void setLineId(String lineId) {
        this.lineId = lineId;
    }

    @Column(name = "line_user_id", length = 100)
    @Size(max = 100)
    public String getLineUserId() {
        return this.lineUserId;
    }

    public void setLineUserId(String lineUserId) {
        this.lineUserId = lineUserId;
    }

    @Column(name = "line_user_name", length = 100)
    @Size(max = 100)
    public String getLineUserName() {
        return this.lineUserName;
    }

    public void setLineUserName(String lineUserName) {
        this.lineUserName = lineUserName;
    }

    @Column(name = "mobile_phone", length = 20)
    @Size(max = 20)
    public String getMobilePhone() {
        return this.mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    @Column(name = "email", length = 200)
    @Size(max = 200)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "county", length = 20)
    @Size(max = 20)
    public String getCounty() {
        return this.county;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    @Column(name = "district", length = 20)
    @Size(max = 20)
    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    @Column(name = "zipcode", length = 10)
    @Size(max = 10)
    public String getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    @Column(name = "address", length = 200)
    @Size(max = 200)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "finished", nullable = false, precision = 10)
    @NotNull
    public Integer getFinished() {
        return this.finished;
    }

    public void setFinished(Integer finished) {
        this.finished = finished;
    }

    @Column(name = "created_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "created_date", nullable = false)
    @NotNull
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "last_modified_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    @Column(name = "last_modified_date", nullable = false)
    @NotNull
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}
